### ISSUE TITLE
please add option categoryLabels to old syntax

### ISSUE THREAD

**Issue by brianpenghe** [tinevez/jyt-matlab#2]
I tried the example but got an error:
data = {randn(25,1),randn(100,1),randn(300,1)};
figure,plotSpread(data,[],[],{'25 pts','100 pts','300 pts'})

Error using plotSpread (line 170)
please add option categoryLabels to old syntax

Any thoughts?

**Comment by tinevez** [comment]
Can you point me to the file where this example is. ?

**Comment by brianpenghe** [comment]
The function is here https://github.com/tinevez/jyt-matlab/blob/c971516bb4b8811e4cdbd813d1a9f9fba9f228f6/fex/plots/plotSpread/plotSpread.m

The example is included in the comments of the script.

**Comment by tinevez** [comment]
The example works on my setup. I suspect a conflict of version since this file originates from the FEX. Can you copy/paste the output of
``` matlab
which plotspread
```

**Comment by brianpenghe** [comment]
I did avoid the function name conflict and the only working plotSpread is here.
/////plotSpread/plotSpread.m

In your plotSpread.m Line 170 is stored the error message. 
But still I don't know how to fix it.
I'm using MATLAB_R2016b on Mac

**Comment by tinevez** [comment]
Hi @brianpenghe 
I don't understand. Can you clarify?
In my case, the `which plotspread` points to the version in fex folder correctly and the example runs fine.

**Comment by brianpenghe** [comment]
@tinevez The problem got solved. 
It turned out that somehow I used a version downloaded here https://www.mathworks.com/help/matlab/ref/plot.html that didn't work for me.
But downloading your Github Zip did the work.

Thank you for your patient replies.

**Comment by tinevez** [comment]
Ok. Sorry I do not understand the fix nor the error source. 
Anyway  the problem is fixed.

**Comment by brianpenghe** [comment]
Do you have a merged version of the two packages ?
https://www.mathworks.com/matlabcentral/fileexchange/23661-violin-plots-for-plotting-multiple-distributions--distributionplot-m-
https://www.mathworks.com/matlabcentral/fileexchange/37105-plot-spread-points--beeswarm-plot-

I noticed that they share some scripts but have different versions?

**Comment by tinevez** [comment]
No, and actually the fex folder is bound to disappear.
It contains contributions from other authors collected on the fex, that my other scripts depend on. I pushed them here on this repo (with proper attributions) because I needed a versioning system that I could keep consistent over several systems.

**Comment by pasand85** [comment]
Hi I have the same problem.
While using plotspread function in the example:

data = {randn(25,1),randn(100,1),randn(300,1)};
figure,plotSpread(data,[],[],{'25 pts','100 pts','300 pts'})

I get the error:

Error using plotSpread (line 170)
please add option categoryLabels to old syntax

Any suggestions?
